//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Borton.Data
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// auto-generated
    /// </summary>
    public partial class BORTONOR
    {
        /// <summary>
        /// auto-generated
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BORTONOR()
        {
            this.FEGYENC = new HashSet<FEGYENC>();
        }

        /// <summary>
        /// auto-generated
        /// </summary>
        public decimal bortonor_ID { get; set; }

        /// <summary>
        /// auto-generated
        /// </summary>
        public Nullable<System.DateTime> munka_kezdete { get; set; }

        /// <summary>
        /// auto-generated
        /// </summary>
        public Nullable<System.DateTime> szuletesi_datum { get; set; }

        /// <summary>
        /// auto-generated
        /// </summary>
        public string szuletesi_hely { get; set; }

        /// <summary>
        /// auto-generated
        /// </summary>
        public string nev { get; set; }

        /// <summary>
        /// auto-generated
        /// </summary>
        public Nullable<decimal> jelveny_szam { get; set; }

        /// <summary>
        /// auto-generated
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FEGYENC> FEGYENC { get; set; }
    }
}
