//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Borton.Data
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// auto-generated
    /// </summary>
    public partial class ELHELYEZES
    {
        /// <summary>
        /// auto-generated
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ELHELYEZES()
        {
            this.FEGYENC = new HashSet<FEGYENC>();
        }

        /// <summary>
        /// auto-generated
        /// </summary>
        public decimal cellaszam { get; set; }

        /// <summary>
        /// auto-generated
        /// </summary>
        public decimal agy { get; set; }

        /// <summary>
        /// auto-generated
        /// </summary>
        public string reszleg { get; set; }

        /// <summary>
        /// auto-generated
        /// </summary>
        public Nullable<decimal> emelet { get; set; }

        /// <summary>
        /// auto-generated
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FEGYENC> FEGYENC { get; set; }
    }
}
