//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Borton.Data
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// auto-generated
    /// </summary>
    public partial class FEGYENC
    {
        /// <summary>
        /// auto-generated
        /// </summary>
        public decimal fegyenc_ID { get; set; }
        /// <summary>
        /// auto-generated
        /// </summary>
        public string nev { get; set; }

        /// <summary>
        /// auto-generated
        /// </summary>
        public string nem { get; set; }

        /// <summary>
        /// auto-generated
        /// </summary>
        public Nullable<System.DateTime> szuletesi_datum { get; set; }

        /// <summary>
        /// auto-generated
        /// </summary>
        public string szuletesi_hely { get; set; }

        /// <summary>
        /// auto-generated
        /// </summary>
        public Nullable<System.DateTime> letoltesi_ido_kezdete { get; set; }

        /// <summary>
        /// auto-generated
        /// </summary>
        public Nullable<decimal> itelet_ID { get; set; }

        /// <summary>
        /// auto-generated
        /// </summary>
        public Nullable<decimal> cellaszam { get; set; }

        /// <summary>
        /// auto-generated
        /// </summary>
        public Nullable<decimal> agy { get; set; }

        /// <summary>
        /// auto-generated
        /// </summary>
        public Nullable<decimal> bortonor_ID { get; set; }

        /// <summary>
        /// auto-generated
        /// </summary>
        public virtual BORTONOR BORTONOR { get; set; }

        /// <summary>
        /// auto-generated
        /// </summary>
        public virtual ELHELYEZES ELHELYEZES { get; set; }

        /// <summary>
        /// auto-generated
        /// </summary>
        public virtual ITELET ITELET { get; set; }
    }
}
