//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Borton.Data
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// auto-generated
    /// </summary>
    public partial class ITELET
    {
        /// <summary>
        /// auto-generated
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ITELET()
        {
            this.FEGYENC = new HashSet<FEGYENC>();
        }

        /// <summary>
        /// auto-generated
        /// </summary>
        public decimal itelet_ID { get; set; }

        /// <summary>
        /// auto-generated
        /// </summary>
        public Nullable<System.DateTime> itelet_datuma { get; set; }

        /// <summary>
        /// auto-generated
        /// </summary>
        public Nullable<decimal> letoltendo_ido { get; set; }

        /// <summary>
        /// auto-generated
        /// </summary>
        public string biro { get; set; }

        /// <summary>
        /// auto-generated
        /// </summary>
        public string ugyved { get; set; }

        /// <summary>
        /// auto-generated
        /// </summary>
        public Nullable<decimal> buntett_ID { get; set; }

        /// <summary>
        /// auto-generated
        /// </summary>
        public virtual BUNTETT BUNTETT { get; set; }

        /// <summary>
        /// auto-generated
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FEGYENC> FEGYENC { get; set; }
    }
}
